#!/bin/bash

# Script de instalação do myvim Pack by Vitor Lobo

# Pedindo acesso root para instalação do vim mypack

if [[ ! $(whoami) = "root" ]]; then

	echo "É necessário a permissão de super usuário (root) para instalação do vim mypack"

else


	echo "O seu sistema é baseado em:
	1 - Redhat/rpm
	2 - Debian/deb
	"

	echo "Digite o número correspondente a questão a cima:";read questao

	# caso seja rpm
	if [[ "$questao" = "1" ]]; then
		#redhat rpm
		diretorio=/home/$USER/.vim/

		# verificar se já contém o vim e git instalado. Caso não, instalá.
		if ! rpm -qa | grep -qw vim-minimal && git ; then

			yum install -y vim-minimal git

		fi



		if [ -d "$diretorio" ]; then

			rm -r /home/$USER/.vim

		else

			mkdir /home/$USER/.vim

		fi

		mv /home/$USER/myvim/.vim /home/$USER/ && sudo rm -R /home/$USER/myvim
		mv /home/$USER/.vim/badwolf.vim /usr/share/vim/vim74/colors/
		mv /home/$USER/.vim/.vimrc /home/$USER/
		mv /home/$USER/.vim/monaco.ttf /usr/share/fonts/



	fi
	# caso seja deb
	if [[ "$questao" = "2" ]]; then
		#debian deb

		if  ! dpkg -s vim && git ; then
			#verificar se já está instalado
			apt-get install vim git -y


		fi

		if [ -d "$diretorio" ]; then

			rm -r $HOME/.vim

		else

			mkdir $HOME/.vim

		fi


		mv $HOME/myvim/.vim $HOME/ && sudo rm -R $HOME/myvim
		mv $HOME/.vim/badwolf.vim /usr/share/vim/vim74/colors/
		mv $HOME/.vim/.vimrc $HOME/
		mv $HOME/.vim/monaco.ttf /usr/share/fonts/

	fi


	echo "Vim pack instalado com sucesso!"
fi

