#!/bin/bash

# Script de instalação do vimfiles Pack by Vitor Lobo

#Capturar o nome do usuário
export usuario=$(whoami)

#Capturar o caminho do diretório home do usuário
export caminho=/home/$usuario

#caminho do .vim no diretório home
export diretoriovim=$caminho/.vim/


echo "O seu sistema é baseado em:

1 - Redhat/rpm
2 - Debian/deb
3 - Arch/pacman
"

echo "Digite o número correspondente a questão a cima:";read questao

echo "Aguarde a configuração e instalação do VIM by Vitor Lobo..."

# caso seja rpm
if [[ "$questao" = "1" ]]; then

	# verificar se já contém o vim e git instalado. Caso não, instalá.
	if ! rpm -qa | grep -qw vim-enhanced && git && tmux && ack && ctags ; then
		# Caso não tenha, será instalado
		sudo -i yum install -y vim-enhanced git tmux ack ctags

	fi


	# Verifica se existe o caminho vimfiles	
	if [ -d "$caminho/vimfiles" ]; then

		echo "Atualizando o vimfiles:"
		git pull
	else	
		# Clonando o vimfiles
		git clone https://github.com/lobocode/vimfiles
	fi



	# if [ -d "$diretoriovim" ]; then

	# sudo -i rm -r $caminho/.vim

	# else

	# sudo -i mkdir $caminho/.vim

	# fi

	cp -r $caminho/vimfiles/.vim $caminho/ 
	sudo -i cp $caminho/.vim/*.vim /usr/share/vim/vim*/colors/
	cp $caminho/.vim/.vimrc $caminho/
	sudo -i cp $caminho/.vim/monaco.ttf /usr/share/fonts/
	echo -e "\nClonando e instalando o Neocomlcache"
	echo -e "Aguarde, este procedimento poderá demorar...\n"

	if [ -d "$caminho/.vim/bundle/neocomplcache.vim" ]; then

		echo "Neocomlcache já está instalado!" 
	else
		cd $caminho/.vim/bundle/ && git clone https://github.com/Shougo/neocomplcache.vim 
	fi
	

	echo "vimfiles instalado com sucesso!!" 

fi

