#!/bin/bash

# Script de instalação do vimfiles Pack by Vitor Lobo

#Capturar o nome do usuário
usuario=$(whoami)

#Capturar o caminho do diretório home do usuário
caminho=/home/$usuario

#caminho do .vim no diretório home
diretoriovim=$caminho/.vim/


echo "O seu sistema é baseado em:
	
	1 - Redhat/rpm
	2 - Debian/deb
	3 - Arch/pacman
	"

echo "Digite o número correspondente a questão a cima:";read questao

echo "Aguarde a configuração e instalação do VIM by Vitor Lobo..."

# caso seja rpm
if [[ "$questao" = "1" ]]; then
		
		# verificar se já contém o vim e git instalado. Caso não, instalá.
		if ! rpm -qa | grep -qw vim-enhanced && git && tmux && ack && ctags ; then

			sudo -i yum install -y vim-enhanced git tmux ack ctags

		fi


		if [ -d "$diretoriovim" ]; then
			
			rm -r $caminho/.vim

			else
				
				mkdir $caminho/.vim

			fi

			mv $caminho/vimfiles/.vim $caminho/ 
			mv $caminho/.vim/*.vim /usr/share/vim/vim*/colors/
			mv $caminho/.vim/.vimrc $caminho/
			mv $caminho/.vim/monaco.ttf /usr/share/fonts/
			rm -R $caminho/vimfiles
			echo -e "\nClonando e instalando o Neocomlcache"
			echo -e "Aguarde, este procedimento poderá demorar...\n"
			
			cd $caminho/.vim/bundle/ && git clone https://github.com/Shougo/neocomplcache.vim 


	fi

	# caso seja deb
	if [[ "$questao" = "2" ]]; then
		#debian deb

		if  ! dpkg-query -l vim git tmux ack-grep ctags ; then
			#verificar se já está instalado
			apt-get install vim git tmux ack-grep cmake ctags -y

		fi



		if [ -d "$diretoriovim" ]; then

			rm -r $caminho/.vim

		else

			mkdir $caminho/.vim

		fi


		mv $caminho/vimfiles/.vim $caminho/ 
		mv $caminho/.vim/*.vim /usr/share/vim/vim*/colors/
		mv $caminho/.vim/.vimrc $caminho/
		rm -R $caminho/vimfiles
	fi

	# caso seja pacman
	if [[ "$questao" = "3" ]]; then
	

		# verificar se já contém o vim e git instalado. Caso não, instalá.
		if ! pacman -Qqe | grep vim git tmux ack ctags ; then

			pacman -S vim git tmux ack ctags --noconfirm

		fi



		if [ -d "$diretoriovim" ]; then

			rm -r $caminho/.vim

		else

			mkdir $caminho/.vim

		fi

		mv $caminho/vimfiles/.vim $caminho/
		mv $caminho/.vim/*.vim /usr/share/vim/vim*/colors/
		mv $caminho/.vim/.vimrc $caminho/
		mv $caminho/.vim/monaco.ttf /usr/share/fonts/
		rm -R $caminho/vimfiles

	fi


	echo "Vim pack instalado com sucesso!"
fi

